import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import {
  LuShield, LuBug, LuRadar, LuBrainCircuit, LuZap, LuGlobe,
  LuCheck, LuArrowRight, LuMenu, LuActivity, LuLock, LuFileText,
} from "react-icons/lu";
import { useState } from "react";

const features = [
  { icon: LuBug, title: "Automated VAPT", desc: "Orchestrate Nmap, Nuclei, ZAP, and 6+ engines across web, network, cloud, and container targets." },
  { icon: LuRadar, title: "24/7 SOC Monitoring", desc: "Correlate Windows, Linux, firewall, and Sysmon telemetry into a single live event stream." },
  { icon: LuBrainCircuit, title: "AI Risk Analysis", desc: "Root-cause analysis, attack-path reconstruction, and patch prioritization generated by AI." },
  { icon: LuGlobe, title: "Threat Intelligence", desc: "Live IOC feeds, CVE tracking, and MITRE ATT&CK technique mapping in one dashboard." },
  { icon: LuZap, title: "Automated Response", desc: "Block IPs, isolate endpoints, and disable accounts with one-click, audited actions." },
  { icon: LuFileText, title: "Compliance Reporting", desc: "Executive, technical, and compliance-ready reports exported to PDF, CSV, or HTML." },
];

const plans = [
  { name: "Starter", price: "$0", tag: "For small teams getting started", features: ["Up to 10 assets", "Weekly vulnerability scans", "Community threat feed", "Email support"] },
  { name: "Professional", price: "$249", tag: "For growing security teams", popular: true, features: ["Up to 250 assets", "Continuous scanning", "AI risk analysis", "SOC live monitoring", "Priority support"] },
  { name: "Enterprise", price: "Custom", tag: "For SOC & MSSP operations", features: ["Unlimited assets", "Dedicated threat intel feed", "Automated response actions", "Custom integrations", "24/7 dedicated support"] },
];

const testimonials = [
  { name: "Priya Nair", role: "CISO, Fintra Bank", quote: "Sentinel cut our mean-time-to-detect by more than half within the first quarter." },
  { name: "Daniel Osei", role: "SOC Lead, Vantar Cloud", quote: "The AI attack-path view turned a two-hour triage into a five-minute read." },
  { name: "Meera Kapoor", role: "Security Director, Nexbridge", quote: "One console for VAPT and SOC finally killed our tool sprawl." },
];

export default function Landing() {
  const [menuOpen, setMenuOpen] = useState(false);
  return (
    <div style={{ backgroundColor: "var(--color-bg)" }} className="min-h-screen text-white overflow-x-hidden">
      {/* Nav */}
      <header className="sticky top-0 z-40 backdrop-blur-md border-b" style={{ backgroundColor: "rgba(11,18,32,0.8)", borderColor: "var(--color-border)" }}>
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ backgroundColor: "var(--color-primary)" }}>
              <LuShield className="text-white text-lg" />
            </div>
            <span className="font-semibold tracking-tight" style={{ fontFamily: "var(--font-display)" }}>SENTINEL</span>
          </div>
          <nav className="hidden md:flex items-center gap-8 text-sm" style={{ color: "var(--color-muted)" }}>
            <a href="#features" className="hover:text-white transition-colors">Features</a>
            <a href="#pricing" className="hover:text-white transition-colors">Pricing</a>
            <a href="#testimonials" className="hover:text-white transition-colors">Customers</a>
            <a href="#contact" className="hover:text-white transition-colors">Contact</a>
          </nav>
          <div className="hidden md:flex items-center gap-3">
            <Link to="/login" className="text-sm font-medium hover:text-white transition-colors" style={{ color: "var(--color-muted)" }}>Log in</Link>
            <Link to="/signup" className="btn-primary text-sm">Start Free Trial</Link>
          </div>
          <button className="md:hidden" onClick={() => setMenuOpen((o) => !o)}><LuMenu className="text-xl" /></button>
        </div>
        {menuOpen && (
          <div className="md:hidden px-6 pb-4 flex flex-col gap-3 text-sm" style={{ color: "var(--color-muted)" }}>
            <a href="#features" onClick={() => setMenuOpen(false)}>Features</a>
            <a href="#pricing" onClick={() => setMenuOpen(false)}>Pricing</a>
            <a href="#testimonials" onClick={() => setMenuOpen(false)}>Customers</a>
            <Link to="/login">Log in</Link>
            <Link to="/signup" className="btn-primary text-center">Start Free Trial</Link>
          </div>
        )}
      </header>

      {/* Hero */}
      <section className="relative max-w-7xl mx-auto px-6 pt-20 pb-24 text-center">
        <div className="absolute inset-0 -z-10 opacity-30" style={{
          backgroundImage: "radial-gradient(circle at 1px 1px, #1F2937 1px, transparent 0)",
          backgroundSize: "32px 32px",
        }} />
        <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
          <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-medium mb-6" style={{ backgroundColor: "rgba(59,130,246,0.1)", color: "var(--color-primary)", border: "1px solid rgba(59,130,246,0.25)" }}>
            <LuActivity className="text-sm" /> Now with autonomous AI triage
          </span>
          <h1 className="text-4xl md:text-6xl font-bold tracking-tight max-w-4xl mx-auto leading-[1.1]" style={{ fontFamily: "var(--font-display)" }}>
            Find the breach<br />before it finds you.
          </h1>
          <p className="mt-6 text-base md:text-lg max-w-2xl mx-auto" style={{ color: "var(--color-muted)" }}>
            Sentinel unifies vulnerability assessment, penetration testing, and SOC monitoring into one AI-powered command center — built for teams that can't afford to be slow.
          </p>
          <div className="mt-8 flex items-center justify-center gap-4 flex-wrap">
            <Link to="/signup" className="btn-primary flex items-center gap-2 px-6 py-3">
              Start Free Trial <LuArrowRight />
            </Link>
            <Link to="/login" className="btn-ghost px-6 py-3">See Live Demo</Link>
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="mt-16 panel p-3 md:p-4 max-w-5xl mx-auto relative"
        >
          <div className="absolute top-0 left-0 right-0 h-[2px] scan-line" style={{ background: "linear-gradient(90deg, transparent, #3B82F6, transparent)" }} />
          <div className="rounded-xl overflow-hidden border" style={{ borderColor: "var(--color-border)" }}>
            <div className="h-9 flex items-center gap-2 px-4" style={{ backgroundColor: "var(--color-surface-2)" }}>
              <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: "#EF4444" }} />
              <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: "#F59E0B" }} />
              <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: "#22C55E" }} />
              <span className="ml-3 text-xs mono" style={{ color: "var(--color-muted)" }}>app.sentinel.security/dashboard</span>
            </div>
            <div className="p-6 md:p-10 grid grid-cols-2 md:grid-cols-4 gap-3" style={{ backgroundColor: "#0D1524" }}>
              {["482 Assets", "17 Critical", "214 Alerts (24h)", "78/100 Score"].map((s) => (
                <div key={s} className="panel p-4 text-left">
                  <div className="w-8 h-8 rounded-lg flex items-center justify-center mb-3" style={{ backgroundColor: "rgba(59,130,246,0.12)" }}>
                    <LuShield style={{ color: "var(--color-primary)" }} />
                  </div>
                  <p className="text-lg font-bold">{s.split(" ")[0]}</p>
                  <p className="text-xs" style={{ color: "var(--color-muted)" }}>{s.split(" ").slice(1).join(" ")}</p>
                </div>
              ))}
            </div>
          </div>
        </motion.div>
      </section>

      {/* Features */}
      <section id="features" className="max-w-7xl mx-auto px-6 py-20">
        <div className="text-center max-w-2xl mx-auto mb-14">
          <h2 className="text-3xl font-bold" style={{ fontFamily: "var(--font-display)" }}>Everything a modern SOC needs</h2>
          <p className="mt-3 text-sm" style={{ color: "var(--color-muted)" }}>From first scan to final response, one platform covers the full lifecycle.</p>
        </div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
          {features.map((f, i) => (
            <motion.div
              key={f.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.05 }}
              className="panel panel-hover p-6"
            >
              <div className="w-11 h-11 rounded-xl flex items-center justify-center mb-4" style={{ backgroundColor: "rgba(59,130,246,0.1)" }}>
                <f.icon className="text-xl" style={{ color: "var(--color-primary)" }} />
              </div>
              <h3 className="font-semibold mb-2">{f.title}</h3>
              <p className="text-sm" style={{ color: "var(--color-muted)" }}>{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="max-w-7xl mx-auto px-6 py-20">
        <div className="text-center max-w-2xl mx-auto mb-14">
          <h2 className="text-3xl font-bold" style={{ fontFamily: "var(--font-display)" }}>Simple, transparent pricing</h2>
          <p className="mt-3 text-sm" style={{ color: "var(--color-muted)" }}>Scale from a single application to a full enterprise estate.</p>
        </div>
        <div className="grid md:grid-cols-3 gap-6 items-stretch">
          {plans.map((p) => (
            <div
              key={p.name}
              className={`panel p-7 flex flex-col relative ${p.popular ? "border-2" : ""}`}
              style={p.popular ? { borderColor: "var(--color-primary)" } : {}}
            >
              {p.popular && (
                <span className="absolute -top-3 left-1/2 -translate-x-1/2 text-[10px] font-bold uppercase tracking-wide px-3 py-1 rounded-full" style={{ backgroundColor: "var(--color-primary)", color: "white" }}>
                  Most Popular
                </span>
              )}
              <h3 className="font-semibold text-lg">{p.name}</h3>
              <p className="text-xs mt-1" style={{ color: "var(--color-muted)" }}>{p.tag}</p>
              <div className="mt-5 flex items-end gap-1">
                <span className="text-3xl font-bold">{p.price}</span>
                {p.price !== "Custom" && <span className="text-sm mb-1" style={{ color: "var(--color-muted)" }}>/mo</span>}
              </div>
              <ul className="mt-6 space-y-3 flex-1">
                {p.features.map((f) => (
                  <li key={f} className="flex items-center gap-2.5 text-sm">
                    <LuCheck className="shrink-0" style={{ color: "var(--color-success)" }} /> {f}
                  </li>
                ))}
              </ul>
              <Link to="/signup" className={p.popular ? "btn-primary text-center mt-7" : "btn-ghost text-center mt-7"}>
                Get Started
              </Link>
            </div>
          ))}
        </div>
      </section>

      {/* Why choose us */}
      <section className="max-w-7xl mx-auto px-6 py-20">
        <div className="panel p-10 md:p-14 grid md:grid-cols-2 gap-10 items-center">
          <div>
            <h2 className="text-3xl font-bold mb-4" style={{ fontFamily: "var(--font-display)" }}>Why security teams choose Sentinel</h2>
            <p className="text-sm mb-6" style={{ color: "var(--color-muted)" }}>
              Legacy tools force analysts to stitch findings together by hand. Sentinel correlates VAPT findings with live SOC telemetry automatically, so risk decisions happen in minutes, not days.
            </p>
            <div className="space-y-4">
              {[
                { icon: LuLock, t: "Zero tool sprawl", d: "One console replaces six disconnected dashboards." },
                { icon: LuBrainCircuit, t: "AI-native triage", d: "Every alert ships with root cause and recommended action." },
                { icon: LuZap, t: "Response in one click", d: "Contain a threat without leaving the platform." },
              ].map((item) => (
                <div key={item.t} className="flex gap-3">
                  <item.icon className="text-lg mt-0.5 shrink-0" style={{ color: "var(--color-primary)" }} />
                  <div>
                    <p className="font-medium text-sm">{item.t}</p>
                    <p className="text-xs" style={{ color: "var(--color-muted)" }}>{item.d}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            {[["99.98%", "Uptime SLA"], ["<5min", "Median Detect Time"], ["1,200+", "Threats Blocked / Day"], ["40+", "Integrations"]].map(([v, l]) => (
              <div key={l} className="panel p-5 text-center">
                <p className="text-2xl font-bold" style={{ color: "var(--color-primary)" }}>{v}</p>
                <p className="text-xs mt-1" style={{ color: "var(--color-muted)" }}>{l}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section id="testimonials" className="max-w-7xl mx-auto px-6 py-20">
        <div className="text-center max-w-2xl mx-auto mb-14">
          <h2 className="text-3xl font-bold" style={{ fontFamily: "var(--font-display)" }}>Trusted by security-first teams</h2>
        </div>
        <div className="grid md:grid-cols-3 gap-6">
          {testimonials.map((t) => (
            <div key={t.name} className="panel p-6">
              <p className="text-sm mb-6" style={{ color: "var(--color-muted)" }}>"{t.quote}"</p>
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 rounded-full flex items-center justify-center text-xs font-bold" style={{ backgroundColor: "var(--color-primary)" }}>
                  {t.name.split(" ").map((n) => n[0]).join("")}
                </div>
                <div>
                  <p className="text-sm font-medium">{t.name}</p>
                  <p className="text-xs" style={{ color: "var(--color-muted)" }}>{t.role}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* CTA + Contact */}
      <section id="contact" className="max-w-7xl mx-auto px-6 py-20">
        <div className="panel p-10 md:p-16 text-center relative overflow-hidden">
          <div className="absolute inset-0 opacity-20" style={{ background: "radial-gradient(circle at 50% 0%, rgba(59,130,246,0.4), transparent 60%)" }} />
          <h2 className="text-3xl font-bold relative" style={{ fontFamily: "var(--font-display)" }}>Ready to see your real attack surface?</h2>
          <p className="mt-3 text-sm max-w-lg mx-auto relative" style={{ color: "var(--color-muted)" }}>
            Start a free trial or talk to our team about deploying Sentinel across your organization.
          </p>
          <div className="mt-8 flex items-center justify-center gap-4 flex-wrap relative">
            <Link to="/signup" className="btn-primary px-6 py-3">Start Free Trial</Link>
            <a href="mailto:sales@sentinel.security" className="btn-ghost px-6 py-3">Contact Sales</a>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t" style={{ borderColor: "var(--color-border)" }}>
        <div className="max-w-7xl mx-auto px-6 py-10 flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2.5">
            <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ backgroundColor: "var(--color-primary)" }}>
              <LuShield className="text-white text-sm" />
            </div>
            <span className="text-sm font-semibold">SENTINEL</span>
          </div>
          <p className="text-xs" style={{ color: "var(--color-muted)" }}>© 2026 Sentinel Security, Inc. All rights reserved.</p>
          <div className="flex items-center gap-5 text-xs" style={{ color: "var(--color-muted)" }}>
            <a href="#" className="hover:text-white">Privacy</a>
            <a href="#" className="hover:text-white">Terms</a>
            <a href="#" className="hover:text-white">Status</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
